import type { Exercise } from "../api/types";

/** Built-in exercise library — admin can add videos via backend later */
export const EXERCISE_LIBRARY: Exercise[] = [
  {
    _id: "ex_001",
    name: "Bench Press",
    targetMuscle: "Chest",
    equipment: "Barbell",
    difficulty: "intermediate",
    sets: 4,
    reps: 10,
    restSeconds: 90,
    thumbnailUrl: "",
    formTips: [
      "Keep your feet flat on the floor",
      "Retract your shoulder blades",
      "Lower the bar to mid-chest",
      "Keep wrists straight",
      "Drive through your heels",
    ],
    commonMistakes: [
      "Bouncing the bar off chest",
      "Flaring elbows too wide",
      "Lifting hips off bench",
      "Uneven grip on bar",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_002",
    name: "Incline Dumbbell Press",
    targetMuscle: "Upper Chest",
    equipment: "Dumbbells",
    difficulty: "intermediate",
    sets: 3,
    reps: 12,
    restSeconds: 60,
    thumbnailUrl: "",
    formTips: [
      "Set bench to 30-45 degrees",
      "Keep shoulders pinned back",
      "Press dumbbells in an arc",
      "Don't lock elbows at top",
    ],
    commonMistakes: [
      "Bench angle too steep",
      "Flaring elbows outward",
      "Arching lower back",
      "Using too much weight",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_003",
    name: "Lat Pulldown",
    targetMuscle: "Back (Lats)",
    equipment: "Cable Machine",
    difficulty: "beginner",
    sets: 4,
    reps: 12,
    restSeconds: 60,
    thumbnailUrl: "",
    formTips: [
      "Grip wider than shoulder width",
      "Lean back slightly",
      "Pull to upper chest",
      "Squeeze shoulder blades",
      "Control the negative",
    ],
    commonMistakes: [
      "Pulling behind the neck",
      "Using momentum to swing",
      "Gripping too narrow",
      "Not fully extending arms",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_004",
    name: "Goblet Squat",
    targetMuscle: "Legs (Quads)",
    equipment: "Dumbbell",
    difficulty: "beginner",
    sets: 3,
    reps: 15,
    restSeconds: 45,
    thumbnailUrl: "",
    formTips: [
      "Hold dumbbell against chest",
      "Keep chest up, back straight",
      "Squat below parallel if possible",
      "Drive through heels",
      "Keep knees tracking over toes",
    ],
    commonMistakes: [
      "Rounding the back",
      "Knees caving inward",
      "Heels lifting off floor",
      "Not going deep enough",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_005",
    name: "Plank",
    targetMuscle: "Core",
    equipment: "Bodyweight",
    difficulty: "beginner",
    sets: 3,
    reps: 1,
    restSeconds: 30,
    formTips: [
      "Keep body in straight line",
      "Engage your core fully",
      "Don't let hips sag",
      "Breathe steadily",
      "Start with 30 sec, build up",
    ],
    commonMistakes: [
      "Hips too high or too low",
      "Holding breath",
      "Looking up (straining neck)",
      "Arching lower back",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_006",
    name: "Shoulder Press",
    targetMuscle: "Shoulders (Delts)",
    equipment: "Dumbbells",
    difficulty: "intermediate",
    sets: 4,
    reps: 10,
    restSeconds: 60,
    thumbnailUrl: "",
    formTips: [
      "Sit with back support",
      "Press dumbbells overhead",
      "Don't lock elbows fully",
      "Control the descent",
      "Keep core engaged",
    ],
    commonMistakes: [
      "Arching the back",
      "Pressing behind the neck",
      "Using too much weight",
      "Partial range of motion",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_007",
    name: "Deadlift",
    targetMuscle: "Back & Legs",
    equipment: "Barbell",
    difficulty: "advanced",
    sets: 3,
    reps: 8,
    restSeconds: 120,
    thumbnailUrl: "",
    formTips: [
      "Bar over mid-foot",
      "Hinge at hips, not squat",
      "Keep bar close to body",
      "Engage lats, lock arms",
      "Drive through heels",
      "Stand tall at top, squeeze glutes",
    ],
    commonMistakes: [
      "Rounding lower back",
      "Starting with hips too low",
      "Bar drifting away from body",
      "Jerking the bar off floor",
      "Hyperextending at top",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_008",
    name: "Squat",
    targetMuscle: "Legs (Quads & Glutes)",
    equipment: "Barbell",
    difficulty: "intermediate",
    sets: 4,
    reps: 10,
    restSeconds: 90,
    thumbnailUrl: "",
    formTips: [
      "Bar across upper back",
      "Chest up, back tight",
      "Break at hips and knees",
      "Go below parallel",
      "Drive through mid-foot",
      "Keep knees out",
    ],
    commonMistakes: [
      "Knees caving in",
      "Heels lifting",
      "Good-morning the weight",
      "Not hitting depth",
      "Looking down",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_009",
    name: "Cable Row",
    targetMuscle: "Back (Mid-back)",
    equipment: "Cable Machine",
    difficulty: "beginner",
    sets: 3,
    reps: 12,
    restSeconds: 60,
    thumbnailUrl: "",
    formTips: [
      "Sit with slight knee bend",
      "Pull handle to lower chest",
      "Squeeze shoulder blades",
      "Control both phases",
      "Keep torso stable",
    ],
    commonMistakes: [
      "Using too much momentum",
      "Rounding the back",
      "Not full range of motion",
      "Pulling too high (to neck)",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_010",
    name: "Triceps Pushdown",
    targetMuscle: "Triceps",
    equipment: "Cable Machine",
    difficulty: "beginner",
    sets: 3,
    reps: 15,
    restSeconds: 45,
    thumbnailUrl: "",
    formTips: [
      "Elbows pinned to sides",
      "Push down with triceps only",
      "Full extension at bottom",
      "Control the return",
      "Don't lean into cable",
    ],
    commonMistakes: [
      "Elbows drifting forward",
      "Using body weight to push",
      "Partial range of motion",
      "Gripping too tight",
    ],
    contentStatus: "placeholder",
  },
  {
    _id: "ex_011",
    name: "Biceps Curl",
    targetMuscle: "Biceps",
    equipment: "Dumbbells",
    difficulty: "beginner",
    sets: 3,
    reps: 12,
    restSeconds: 45,
    thumbnailUrl: "",
    formTips: [
      "Elbows at sides, don't swing",
      "Curl with control",
      "Squeeze at top",
      "Full range of motion",
      "Lower slowly (2-3 sec)",
    ],
    commonMistakes: [
      "Swinging the weight",
      "Elbows moving forward",
      "Not fully extending",
      "Using too much weight",
    ],
    contentStatus: "placeholder",
  },
];

export const exerciseService = {
  getAll: (): Exercise[] => EXERCISE_LIBRARY,

  getById: (id: string): Exercise | undefined =>
    EXERCISE_LIBRARY.find((ex) => ex._id === id),

  getByMuscle: (muscle: string): Exercise[] =>
    EXERCISE_LIBRARY.filter((ex) =>
      ex.targetMuscle.toLowerCase().includes(muscle.toLowerCase())
    ),

  getByDifficulty: (difficulty: Exercise["difficulty"]): Exercise[] =>
    EXERCISE_LIBRARY.filter((ex) => ex.difficulty === difficulty),

  search: (query: string): Exercise[] =>
    EXERCISE_LIBRARY.filter(
      (ex) =>
        ex.name.toLowerCase().includes(query.toLowerCase()) ||
        ex.targetMuscle.toLowerCase().includes(query.toLowerCase()) ||
        ex.equipment.toLowerCase().includes(query.toLowerCase())
    ),
};
